### ISSUE TITLE
Certificate is Blank

### ISSUE THREAD

**Issue by kbberry** [markn86/moodle-mod_customcert#94] opened 2017-03-15 12:32 UTC
Hello,

I have read through the previous tickets submitted regarding the blank certificate issue and date object. I have removed the date from my certificate, re-added the date, changed the date type, etc. but it is still displaying and downloading a blank certificate. 

It shows properly in the plugin preview but blank when downloaded.

I am using Moodle v. 3.2.1

I turned on developer debugging and error reporting but I do not get any error codes, the certificate automatically downloads. Please advise.

**Comment by kbberry** [comment] 2017-03-23 19:40
Hello any ideas for how to fix this would be greatly appreciated.

**Comment by markn86** [comment] 2017-03-27 11:03
Have you tried viewing the certificate as a separate user (someone who may have a date?). Is it possible the currently logged in user who you are viewing the certificate for does not have data for that field?

**Comment by markn86** [comment] 2017-03-28 03:41
Is the issue experienced in #84 the same?

**Comment by kbberry** [comment] 2017-04-10 16:25
Sorry I am just now seeing this response. I will give that a try.

**Comment by markn86** [comment] 2017-04-27 07:48
Closing due to being unable to reproduce.

**Closed by markn86** 2017-04-27 07:48 UTC
