### ISSUE TITLE
Add Elemen to template = Error 500

### ISSUE THREAD

**Issue by rrenedo** [markn86/moodle-mod_customcert#139] opened 2017-09-28 17:33 UTC
Please can you help me.
when I want to add a new element, the browser returns an ERROR 500.
The option to add a new element type (Backgrount) Its working fine, but if I add an element of type (studentName) I get the error 500.

**Comment by markn86** [comment] 2017-10-02 04:15
Can you turn on debugging (https://docs.moodle.org/32/en/Debugging) and visit the page to see what the error message is exactly? Also, what version of Moodle AND the plugin are you using?

**Comment by rrenedo** [comment] 2017-10-03 11:23
Hi,

The mode Debug not show me nothing.
The problem is when add new element. The server in error_log in apache show
ERROR 500 but nothing more...
The problem is in the "mod/customcert/edit_element.php" I think the
$element is empty...

Please can you help me.

Thenks.

Ruben




2017-10-02 6:15 GMT+02:00 Mark Nelson <notifications@github.com>:

**Comment by markn86** [comment] 2017-10-04 10:51
What level of debugging do you have it on? If you get an ERROR 500 and you have error reporting on then you *should* see an an error message. I can't help without seeing this error. Maybe have a read of https://stackoverflow.com/questions/7149030/php-return-500-error-but-no-error-log.

**Comment by markn86** [comment] 2017-10-13 04:01
I am closing this issue as I can not replicate it. I believe it is a server configuration issue (check permissions on folders and files) and not a bug in the code.

**Closed by markn86** 2017-10-13 04:01 UTC
