### ISSUE TITLE
Removed the 'posx' and 'posy' form elements - can we have them back?

### ISSUE THREAD

**Issue by ShelterJames** [markn86/moodle-mod_customcert#41] opened 2016-09-21 13:57 UTC
Hello Mark.

Firstly, thanks for your work on this module.

We are on Moodle 3.0. I see recently, the "Position X" and "Position Y" form boxes were removed. https://github.com/markn86/moodle-mod_customcert/commit/ed93542c0c6eed39d991050f88a40133ac06b319

I guess the thinking was this was confusing and people should use the "Reposition GUI" instead?

Um .... can we have the "Position X" and "Position Y" form boxes back? They allow us to get much finer control than with just the GUI.

Could there maybe be an option to decide if they were shown or not?

Thanks,
James

**Comment by markn86** [comment] 2016-10-03 11:15
Hi James,

Sorry, didn't expect to have people wanting to use that feature over the GUI! May I ask why? Would https://github.com/markn86/moodle-mod_customcert/issues/37 achieve your goals?

**Comment by ShelterJames** [comment] 2016-10-03 12:26
"Position X" and "Position Y" form boxes allow us to get much finer control than with just the GUI. The GUI is not suitable due to the problems mentioned in #37 about dragging and dropping an element into the exact place, especially if you are trying to get elements to line up with each other or center exactly. Also, dragging and dropping becomes even less exact when your designing an A4 sheet but the window you have to drag and drop in is about quarter the size of A4.

I think: a gridbox would only solve this issue if we could select where the grid lines where ourselves.

And even then, it's not perfect - we also have a situation where someone is copying a certificate from a testing to a dev server. And we will have situations where people will be basically copying a certificate from course to course, with only minor changes. In that case, it's easier if there is just data they can copy (X,Y co-ords) that instantly gives an exact match than having to again try and get everything to line up with the mouse.  This is maybe however a edge case, and some of this could be dealt with by a "copy cert" feature.

At least, until alternatives have been fully sorted out, can this feature be put back? Maybe behind a config option, as said, if that helps with a usable UX - I do accept not everyone will like X&Y!

**Comment by markn86** [comment] 2016-10-04 07:41
Ok, thanks James.

I will look at adding it back.

I may introduce an activity setting that determines if these positions are displayed or not. I can see them causing a lot of confusion to teachers who have no idea what they refer to, which was my main reason to remove them in the first place but from what you have said I can see people will still use them.

**Comment by ShelterJames** [comment] 2016-10-04 11:37
The activity setting sounds good. 

Thank you (and for the mod) :-)

**Comment by markn86** [comment] 2016-10-05 09:44
Great, now I just need to find some time to get it done. :)

**Comment by markn86** [comment] 2016-10-21 13:11
Working on this now as I wait for my flight. Hopefully gives me enough time. :)

**Comment by markn86** [comment] 2016-10-21 13:49
I created a simple fix. However, there is an issue now when editing an element (by clicking on it) on the 'Reposition elements' page. Once you submit the form, it saves the data, then returns the HTML to display. However, I would now have to work out where to display the HTML I return as the position may have changed. Right now this is done at the start of the page by a YUI module, where as I am using an AMD module for the WS call. I need to think about this more .. perhaps it can be done in another issue.

**Comment by ShelterJames** [comment] 2016-10-24 08:05
So to get my head around this, this problem occurs if two people try to position elements at once? One hand editing X & Y, and the other editing using the positional editor?

Couldn't this problem happen anyway already? Currently, if two people both open the positional editor and start editing, the saves would get more and more divergent if the editors don't reload?

I can think of special measures, but they are all quite complex. Is there anywhere else in Moodle that has measures in place to help if two people edit the same thing at once?

I'd also argue this is such a minor edge case - hopefully a complex answer shouldn't be needed here :-)

**Comment by markn86** [comment] 2016-11-09 03:16
Sorry for the delayed response. I have been on holiday the past few weeks and am just catching up on emails now. Nope, different issue James. The issue is changing the position of the element in the form in the pop-up, and then saving, but the position not changing.

**Comment by markn86** [comment] 2016-12-30 05:42
Created a setting to add this back. It also works on the rearrange page - changing the posx or posy values will move the element on that page. Closing this issue.

**Closed by markn86** 2016-12-30 05:42 UTC
