### ISSUE TITLE
Change certificate pdf file name

### ISSUE THREAD

**Issue by ankitkatmore** [markn86/moodle-mod_customcert#201] opened 2018-06-12 11:31 UTC
Hello team,

When we download the certificate in PDF format. I need to change the filename as user's name. I have changed the filename in generate_pdf function but that  not working. Can you please let me know how can  i change the filename of PDF. Please let me know me asap. 

Thanks

**Comment by markn86** [comment] 2018-07-12 11:33
Closing as a duplicate of #132.

**Closed by markn86** 2018-07-12 11:33 UTC
