### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by CognitaDev** [markn86/moodle-mod_customcert#218] opened 2018-07-19 10:52 UTC
Hi,
in Moodle 3.3.6, custom certificate 3.3.14, 2017050514, after clicking Save changes and preview there is an error:  exception - TCPDF ERROR: Some data has already been output, can't send PDF file
×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 2927 of /lib/tcpdf/tcpdf.php: Exception thrown
line 7643 of /lib/tcpdf/tcpdf.php: call to TCPDF->Error()
line 190 of /lib/pdflib.php: call to TCPDF->Output()
line 311 of /mod/customcert/classes/template.php: call to pdf->Output()
line 233 of /mod/customcert/edit.php: call to mod_customcert\template->generate_pdf()
Any changes in plugin to fix this error?

**Comment by markn86** [comment] 2018-07-23 02:59
Hi, thanks for the report.

I was not able to replicate this issue.

Do you know what the output was that was displayed before the download commenced? What elements do you have added to your certificate?

**Comment by CognitaDev** [comment] 2018-07-23 21:43
Hi,
thanks for the reply. Save changes and preview isn't working from start. This is the only certificate and it contains background image (A4) and one text box.  Perhaps removing plugin and installing it again could fix the issue?

**Comment by markn86** [comment] 2018-07-24 03:09
Is there any information in the 'Output buffer' which can tell me what is displayed?

For example, I intentionally triggered this error by outputting the string 'hey' and the error message included this string in the output under the 'Output buffer' heading. See screenshot -

![screen shot 2018-07-24 at 11 08 19 am](https://user-images.githubusercontent.com/783213/43114498-0539359a-8f32-11e8-8cf4-ac9d598ee6d6.png)

**Comment by CognitaDev** [comment] 2018-07-24 19:50
There is no information in output buffer. 
![errortcpdf](https://user-images.githubusercontent.com/34572460/43162455-5776bbe4-8f8b-11e8-83ed-9c7a3bd818ff.jpg)
I enabled chrome dev console, and there's an error: Failed to load resource: the server responded with a status of 404 (Not Found)   /mod/customcert/edit.php:1

**Comment by psywhale** [comment] 2018-08-16 14:47
Moodle 3.4.3 (Build: 20180517) 
git pulled branch MOODLE_34_STABLE  
module version: 2017111305

404 error is now from view.php

**Comment by markn86** [comment] 2018-08-23 12:44
@psywhale that sounds like a permission issue with the view.php file. Have you checked permissions?

**Comment by psywhale** [comment] 2018-08-23 14:02
Yes I have. 
![screenshot from 2018-08-23 08-35-10](https://user-images.githubusercontent.com/959517/44529240-3695a880-a6b1-11e8-9925-bd95f9d9e9e3.png)

I get the 404 only when I try to download or preview the Cert
When I Download the cert: 

![screenshot from 2018-08-23 08-47-04](https://user-images.githubusercontent.com/959517/44529318-6644b080-a6b1-11e8-92b0-4bef072aa7a8.png)

When I save and preview the cert

![screenshot from 2018-08-23 08-53-32](https://user-images.githubusercontent.com/959517/44529647-3b0e9100-a6b2-11e8-88a5-a0a339f70636.png)

This is in the apache error log:
``
[Thu Aug 23 08:38:36.986708 2018] [:error] [pid 25762] [client <censored ip>:63922] Default exception handler: Exception - TCPDF ERROR: Some data has already been output, can't send PDF file Debug: \nError code: generalexceptionmessage\n* line 2927 of /lib/tcpdf/tcpdf.php: Exception thrown\n* line 7649 of /lib/tcpdf/tcpdf.php: call to TCPDF->Error()\n* line 190 of /lib/pdflib.php: call to TCPDF->Output()\n* line 311 of /mod/customcert/classes/template.php: call to pdf->Output()\n* line 185 of /mod/customcert/view.php: call to mod_customcert\\template->generate_pdf()\n, referer: https://moodle.wosc.edu/mod/customcert/view.php?id=26160
``

**Comment by psywhale** [comment] 2018-08-23 14:28
output buffer issues, perhaps.  
I have added these lines to view.php to try to fix / diagnose problem:
![screenshot from 2018-08-23 09-26-42](https://user-images.githubusercontent.com/959517/44531546-a9ede900-a6b6-11e8-9225-7205c6eac330.png)

Incognito mode, so no plugins will interfere, I get 3 blank lines in my output buffer.

![screenshot from 2018-08-23 09-28-14](https://user-images.githubusercontent.com/959517/44531636-e6214980-a6b6-11e8-8ce2-3ec361f8e075.png)

**Comment by psywhale** [comment] 2018-08-23 15:14
I got a PR that fixed the issue for me.  #229

**Comment by CognitaDev** [comment] 2018-08-23 16:02
Added ob_clean to edit.php, it removes the TCPDF ERROR: Some data has already been output, can't send PDF file error, but generated PDF file is impossible to open. Error: failed to load PDF document.
![untitled](https://user-images.githubusercontent.com/34572460/44537317-bbf37a00-a6fe-11e8-8a1c-3b6a15095db5.jpg)

**Comment by psywhale** [comment] 2018-08-23 16:34
What are your settings for the Certificate? With default values, I still
get a blank pdf.



[image: Western Oklahoma State College Logo] <https://www.wosc.edu/>Brian
Carpenter
Information Systems Specialist
Western Oklahoma State College <https://www.wosc.edu/>
2801 N. Main St.  *|*  Altus, OK 73521
<https://www.google.com/maps/place/Western+Oklahoma+State+College+Main+Building,+Altus,+OK+73521/@34.6694147,-99.3372287,18.87z/data=!3m1!5s0x87ab653a7bb9cc6f:0xd1063be3c99517db!4m5!3m4!1s0x87ab653a7bbd0569:0xc65b112658cc9ef!8m2!3d34.6689441!4d-99.336963>
(580) 477-7919  *|*  Office: HLC 126
[image: wosc facebook] <https://www.wosc.edu/facebook> [image: wosc
instagram] <https://www.wosc.edu/instagram> [image: wosc twitter]
<https://www.wosc.edu/twitter> [image: wosc snapchat]
<https://snapchat.com/add/woscevents>

The mission of Western Oklahoma State College is to provide high quality
education, support student success, and empower individuals to become
productive members of local, regional, and global communities.

**Comment by psywhale** [comment] 2018-08-23 16:36
What are your settings for the certificate? With default values, I download a blank page.

**Comment by CognitaDev** [comment] 2018-08-24 08:38
default settings, as for the certificate elements and dimensions: 210 x 297, 0 margin, background image + 4 text elements. This error occurs even with a blank new certificate.

**Comment by psywhale** [comment] 2018-08-24 13:46
This may be a different bug... 

I suggest downloading moodle packages designed to run on your local machine. This will be a base install with no extra plugins. That way no other plugins,blocks,themes, etc will interfere. Install the customcert module only and see if you still have this problem. It could be any block/plugin throwing extra bits into the stream.

https://download.moodle.org/macosx/
https://download.moodle.org/windows/

**Comment by markn86** [comment] 2018-12-18 03:44
I am going to close this as I cannot reproduce it. If you can provide some replication steps for me on a vanilla installation with just the Custom Certificate installed I will happily re-open and fix it.

**Closed by markn86** 2018-12-18 03:44 UTC
Labels: Waiting for response
