### ISSUE TITLE
DOWNLOAD CERTIFICATE FOR ALL PARTICIPANTS IN ONE GO

### ISSUE THREAD

**Issue by Venkatesh1985** [markn86/moodle-mod_customcert#234] opened 2018-09-12 08:05 UTC
Using the Admin or Teacher account I want to download certificates of all participants in a one go. This will help in distributing physical copies of the certificates as the teacher can download and print all of them in one go.

**Comment by markn86** [comment] 2018-10-15 03:12
Closing as a duplicate of #205.

**Closed by markn86** 2018-10-15 03:12 UTC
