### ISSUE TITLE
Positioning elements in A4 landscape

### ISSUE THREAD

**Issue by tbahula** [markn86/moodle-mod_customcert#93] opened 2017-03-08 20:34 UTC
Using Custom Certificate plugin 3,1 (Build: 2016052307)
on Moodle 3.1.4 (Build: 20170223)

When attempting to position elements on an A4 landscape layout, all elements are shifted to the left in the resulting PDF. Positioning elements on Letter landscape layout worked as expected.

![image](https://cloud.githubusercontent.com/assets/14959510/23722716/718f36ea-0414-11e7-9dbf-defa9a40b87b.png)

![image](https://cloud.githubusercontent.com/assets/14959510/23722706/68ca8f14-0414-11e7-942d-cfbe777804b0.png)

[A4 (4).pdf](https://github.com/markn86/moodle-mod_customcert/files/828889/A4.4.pdf)

**Comment by markn86** [comment] 2017-03-28 03:36
Thanks for the report. This is tricky since the HTML and PDF are rendered using two completely different libraries and making sure they always match is hard. Will have to investigate this further when I have time.

**Comment by markn86** [comment] 2017-05-31 08:24
Looking at the screenshot - I think this may be because of the margin settings you have.

**Comment by tbahula** [comment] 2017-05-31 14:25
The paper size is standard A4 landscape. The margin settings seem natural and worked for letter-sized paper. What margin settings do you suggest?

**Comment by markn86** [comment] 2017-06-01 03:03
Sorry, I should have opened up the PDF you supplied. I see now that the margin is breaking badly in the PDF and does not reflect the reposition page.

**Comment by markn86** [comment] 2017-06-01 04:05
I was unable to reproduce this. Please see the following screenshots and resulting PDF. Can you update your plugin to see if this fixes it?

![Edit custom certificate](https://cloud.githubusercontent.com/assets/783213/26664200/4423982c-46c2-11e7-8bb6-5d198fc3368c.png)

![Reposition page](https://cloud.githubusercontent.com/assets/783213/26664201/47629466-46c2-11e7-8333-9d36af2f88c1.png)

[A4_on_side.pdf](https://github.com/markn86/moodle-mod_customcert/files/1043578/A4_on_side.pdf)

**Comment by tbahula** [comment] 2017-07-20 21:12
I got around to testing this again. We are now running Build 2016052312.

I encountered the same problem as before on Chrome, but not on FireFox. It appears that this is browser related. Please see if you can reproduce the problem using Chrome.

**Comment by markn86** [comment] 2017-07-24 10:10
The only thing that should be browser dependent is the reposition page, but they are both displaying as expected on Chrome and FF, correct? So, I wonder if it is actually an issue with the PDF creation.

I tried on Chrome and it worked as expected.

**Comment by markn86** [comment] 2017-09-09 07:18
I am going to close this as I can not replicate it.

**Closed by markn86** 2017-09-09 07:18 UTC
Labels: bug
