### ISSUE TITLE
Set url of an image from the custom field.

### ISSUE THREAD

**Issue by rajeshsnadar** [markn86/moodle-mod_customcert#109] opened 2017-05-02 10:18 UTC
I want the image to be picked dynamically from the URL that is stored on to the database in the users custom field.

**Comment by markn86** [comment] 2017-05-30 09:58
Closing as duplicate of #77.

**Closed by markn86** 2017-05-30 09:58 UTC

**Comment by rajeshsnadar** [comment] 2017-05-30 10:09
Hello Mark,
The scenario is such that i want the users profile picture in the certificate, But not the one that the moodle uses. It a custom profile picture whose path is stored in the database i.e an extra column is created in the mdl_user table to store the image path. So just want that path to be picked as the profile picture in the certificate.

If i could find some help it would be helpful.

Thanks & Regards
Rajesh

**Comment by markn86** [comment] 2017-05-30 10:12
Thanks Rajesh,

Please keep the discussion on the issue #77. I can see this being useful but no point having multiple issues about the same thing.
