### ISSUE TITLE
How To Make Link Moodle Mobile 3.5 in App

### ISSUE THREAD

**Issue by DeeSouza** [markn86/moodle-mod_customcert#290] opened 2019-06-05 18:51 UTC
I'm developing a plugin to work on Moodle Mobile 3.5.
I did a page that show the modules from course.

One of them is the Custom Cert. 

To open a module within the app I'm doing so: 

`<a href="http://hmg.upldesenvolve.com.br/moodle/mod/resource/view.php?id=109" core-link capture="true" inApp="true">`

Doing this the app understands automatically that the module can be opened inside of the app component. But, when I open the module **Custom Cert** in my page, instead of opening in the app, it redirects to the module URL on the browser.

How can I make the Custom Cert module behave the same as the other modules inside app?

**Comment by markn86** [comment] 2019-06-06 09:04
Sorry, tbh I am not sure. I developed the mobile capability for this plugin a while ago.

@dpalou or @jleyva would be the ones to ask about this. I would also suggesting posting on the moodle.org forums.

**Comment by dpalou** [comment] 2019-06-07 08:42
Hi,

here's an example on how to do it:

https://docs.moodle.org/dev/Mobile_support_for_plugins#Module_link_handler

Cheers,
Dani

**Comment by DeeSouza** [comment] 2019-06-10 17:24
> Hi,
> 
> here's an example on how to do it:
> 
> https://docs.moodle.org/dev/Mobile_support_for_plugins#Module_link_handler
> 
> Cheers,
> Dani

Thanks for the your answer.

But, I get the javascript code and put in my file JS that read the app, in the parameter `javascript`.

For example:

![image](https://user-images.githubusercontent.com/12430887/59213034-4fad0e80-8b8a-11e9-96f7-1487831d0523.png)

I did and doesn't work.

How to use?

Thanks!

**Comment by dpalou** [comment] 2019-06-12 08:20
Hi Diego,

that code looks fine, I guess the problem is in the JS code itself. I recommend you to post [in the forums](https://moodle.org/mod/forum/view.php?id=7798), there are other developers in there that could be able to help you :)

Cheers,
Dani

**Comment by markn86** [comment] 2019-06-12 15:49
Thanks Dani,

I am closing this now as it seems to be unrelated to the module itself.

**Closed by markn86** 2019-06-12 15:49 UTC
