### ISSUE TITLE
Sending email to nonediting teacher instead of teacher

### ISSUE THREAD

**Issue by Markrico** [markn86/moodle-mod_customcert#247] opened 2018-10-28 15:47 UTC
Hello,

Is there a simple way to change the email teacher so that it emails the nonediting teacher. 

Thank-you very much for any help you can provide. 

Mark

**Comment by markn86** [comment] 2018-12-17 02:18
Closing as a duplicate of #248

**Closed by markn86** 2018-12-17 02:18 UTC
Labels: duplicate
