### ISSUE TITLE
Need to email nonediting teacher and not teacher. 

### ISSUE THREAD

**Issue by Markrico** [markn86/moodle-mod_customcert#246] opened 2018-10-24 19:28 UTC
Hi, 

I love this plugin as it is very useful and easy to use to make custom certificates. 
Is there a way to get it to email the non-editing teacher instead of the teacher. Thank-you very help for any help you can provide. 

Mark

**Comment by markn86** [comment] 2018-12-17 02:19
Closing as a duplicate of #248.

**Closed by markn86** 2018-12-17 02:19 UTC
