### ISSUE TITLE
Certificate appears blank within course

### ISSUE THREAD

**Issue by Leoracejsa** [markn86/moodle-mod_customcert#84] opened 2017-02-14 01:25 UTC
Hi mark,

I'm having trouble viewing the custom certificate.

First I loaded the image of my certificate and then I created everything custom.

When I place it within a discipline, it prints the certificate blank

![1](https://cloud.githubusercontent.com/assets/6587097/22910689/d7905b06-f242-11e6-8709-e7f1bd751db2.jpg)
![2](https://cloud.githubusercontent.com/assets/6587097/22910691/d79faebc-f242-11e6-9db3-5dd6787e7871.jpg)
![3](https://cloud.githubusercontent.com/assets/6587097/22910692/d7ad5364-f242-11e6-98a8-465005c5c321.jpg)
![4](https://cloud.githubusercontent.com/assets/6587097/22910749/2065093a-f243-11e6-827d-1bcbbb4416d3.jpg)

**Comment by markn86** [comment] 2017-02-14 04:11
Hi!

Have you taken a look at #34? I would also suggest turning on debugging (see https://docs.moodle.org/32/en/Debugging) so you can see any potential error messages.

Cheers!

**Comment by Leoracejsa** [comment] 2017-02-14 12:55
I did not find anything in this issue informed ... I'm using version 3.2 of moodle and the plugin ... everything is fine, but at the time of downloading the pdf in the course, it comes in white.

Inside the plugin configuration area, I can preview it, but the course does not appear

**Comment by markn86** [comment] 2017-02-15 02:56
Do you have a date or grade element? Did you turn on debugging to see why it is blank? There is likely an error that has occurred and knowing the stack trace would go a long way into helping me solve this.

**Comment by markn86** [comment] 2017-03-05 07:04
Any updates on this? Otherwise I will close it as I can not reproduce the issue.

**Comment by markn86** [comment] 2017-04-27 07:48
Closing as I cannot reproduce.

**Closed** 2017-04-27 07:48 UTC
